/**
 * A JFrame that a user uses to add a comment to an application
 */

import java.awt.Color;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.border.Border;

public class AddCommentJFrame extends javax.swing.JFrame {

    public AddCommentJFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
        Border bd = BorderFactory.createMatteBorder(3, 3, 3, 3, Color.white);
        jPanel1.setBorder(bd);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jScrollBar1 = new javax.swing.JScrollBar();
        jPanel1 = new javax.swing.JPanel();
        jPanel_portal = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel_close = new javax.swing.JLabel();
        jLabel_minimizeWindow = new javax.swing.JLabel();
        jPanel_appComment = new javax.swing.JPanel();
        jLabel_appName = new javax.swing.JLabel();
        jLabel_comment = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea_comment = new javax.swing.JTextArea();
        jTextField_appName = new javax.swing.JTextField();
        jButton_add = new javax.swing.JButton();
        jLabel_goToDashboard = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(2, 48, 71));
        jPanel1.setAutoscrolls(true);

        jPanel_portal.setBackground(new java.awt.Color(235, 183, 3));

        jLabel1.setBackground(new java.awt.Color(235, 183, 55));
        jLabel1.setFont(new java.awt.Font("Gurmukhi MN", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(61, 90, 128));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Add Comment Portal");

        javax.swing.GroupLayout jPanel_portalLayout = new javax.swing.GroupLayout(jPanel_portal);
        jPanel_portal.setLayout(jPanel_portalLayout);
        jPanel_portalLayout.setHorizontalGroup(
            jPanel_portalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_portalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel_portalLayout.setVerticalGroup(
            jPanel_portalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_portalLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(27, 27, 27))
        );

        jLabel_close.setBackground(new java.awt.Color(2, 48, 71));
        jLabel_close.setFont(new java.awt.Font("Lucida Grande", 0, 28)); // NOI18N
        jLabel_close.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_close.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_close.setText("x");
        jLabel_close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_close.setOpaque(true);
        jLabel_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_closeMouseClicked(evt);
            }
        });

        jLabel_minimizeWindow.setBackground(new java.awt.Color(2, 48, 71));
        jLabel_minimizeWindow.setFont(new java.awt.Font("Lucida Grande", 0, 28)); // NOI18N
        jLabel_minimizeWindow.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_minimizeWindow.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_minimizeWindow.setText("-");
        jLabel_minimizeWindow.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_minimizeWindow.setOpaque(true);
        jLabel_minimizeWindow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_minimizeWindowMouseClicked(evt);
            }
        });

        jPanel_appComment.setBackground(new java.awt.Color(2, 48, 71));

        jLabel_appName.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel_appName.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_appName.setText("App name");

        jLabel_comment.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel_comment.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_comment.setText("Comment");

        jTextArea_comment.setColumns(20);
        jTextArea_comment.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        jTextArea_comment.setRows(5);
        jScrollPane1.setViewportView(jTextArea_comment);

        jTextField_appName.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N

        jButton_add.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jButton_add.setText("Add");
        jButton_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_addActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_appCommentLayout = new javax.swing.GroupLayout(jPanel_appComment);
        jPanel_appComment.setLayout(jPanel_appCommentLayout);
        jPanel_appCommentLayout.setHorizontalGroup(
            jPanel_appCommentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_appCommentLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_appCommentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_appCommentLayout.createSequentialGroup()
                        .addComponent(jLabel_appName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_appName))
                    .addGroup(jPanel_appCommentLayout.createSequentialGroup()
                        .addComponent(jLabel_comment)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1)))
                .addContainerGap())
            .addGroup(jPanel_appCommentLayout.createSequentialGroup()
                .addGap(168, 168, 168)
                .addComponent(jButton_add, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_appCommentLayout.setVerticalGroup(
            jPanel_appCommentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_appCommentLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_appCommentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_appName, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_appName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel_appCommentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_comment, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(jButton_add, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel_goToDashboard.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel_goToDashboard.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_goToDashboard.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_goToDashboard.setText("Go to dashboard");
        jLabel_goToDashboard.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_goToDashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_goToDashboardMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel_minimizeWindow, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel_close, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jPanel_portal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jPanel_appComment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(jLabel_goToDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_close, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_minimizeWindow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(31, 31, 31)
                .addComponent(jPanel_portal, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel_appComment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jLabel_goToDashboard)
                .addContainerGap(87, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>                        

    /**
     * Minimize window
     */
    private void jLabel_minimizeWindowMouseClicked(java.awt.event.MouseEvent evt) {                                                   
        this.setState(JFrame.ICONIFIED);
    }                                                  

    /**
     * Close window
     */
    private void jLabel_closeMouseClicked(java.awt.event.MouseEvent evt) {                                          
        System.exit(0);
    }                                         

    /**
     * Open dashboard and dispose this jframe
     */
    private void jLabel_goToDashboardMouseClicked(java.awt.event.MouseEvent evt) {                                                  
        DashboardJFrame dashboard = new DashboardJFrame();
        dashboard.setVisible(true);
        dashboard.pack();
        dashboard.setLocationRelativeTo(null);
        dashboard.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose(); 
    }                                                 

    /**
     * Add comment to the application if the appName entered is valid
     * If not valid, show error message
     */
    private void jButton_addActionPerformed(java.awt.event.ActionEvent evt) {                                            
        String appName = jTextField_appName.getText();
        String comment = jTextArea_comment.getText();
        
        PreparedStatement ps;
        ResultSet rs;
        String searchQuery = "SELECT * FROM `AppInfo` WHERE `appName` = ?";
        try {
            ps = ConnectData.getConnection().prepareStatement(searchQuery);
            ps.setString(1, appName);

            rs = ps.executeQuery();
            if(!rs.next() || appName.trim().equals("")) {
                JOptionPane.showMessageDialog(null, "Invalid application name");
            } else if (comment.trim().equals("")) {
                JOptionPane.showMessageDialog(null, "Invalid comment");
            } else {
                try {
                    String insertQuery = "INSERT INTO `AppComment`(`appName`, `appComment`) VALUES (?,?)";

                    ps = ConnectData.getConnection().prepareStatement(insertQuery);
                    ps.setString(1, appName);
                    ps.setString(2, comment);

                    if(ps.executeUpdate() > 0) {
                        JOptionPane.showMessageDialog(null, "Comment added!");
                    }

                } catch (SQLException ex) {
                    Logger.getLogger(AddCommentJFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(AddCommentJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }                                           

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddCommentJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton_add;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel_appName;
    private javax.swing.JLabel jLabel_close;
    private javax.swing.JLabel jLabel_comment;
    private javax.swing.JLabel jLabel_goToDashboard;
    private javax.swing.JLabel jLabel_minimizeWindow;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel_appComment;
    private javax.swing.JPanel jPanel_portal;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea_comment;
    private javax.swing.JTextField jTextField_appName;
    // End of variables declaration                   
}
