
import java.awt.Color;
import java.awt.Font;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.border.Border;
import javax.swing.table.DefaultTableModel;


public class CommentListJFrame extends javax.swing.JFrame {

    /**
     * Creates new form DashboardJFrame
     */
    public CommentListJFrame() {
        initComponents();
        this.setLocationRelativeTo(null); //Center

        Border bd = BorderFactory.createMatteBorder(3, 3, 3, 3, Color.white);
        jPanel1.setBorder(bd);
        
        // jTable
        displayFilteredApps(); // Connect with database
        jTable_commentTable.setSelectionBackground(new Color(2,48,71));
        jTable_commentTable.setSelectionForeground(new Color(235,183,3));
        jTable_commentTable.setBackground(new Color(240, 239, 235));
        jTable_commentTable.setRowHeight(50);
        jTable_commentTable.getTableHeader().setBackground(new Color(240, 239, 235));
        jTable_commentTable.getTableHeader().setFont(new Font("Lucida Grande", Font.BOLD, 15));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel_sidePanel = new javax.swing.JPanel();
        jLabel_dashboard = new javax.swing.JLabel();
        jPanel_topPanel = new javax.swing.JPanel();
        jLabel_minimize = new javax.swing.JLabel();
        jLabel_close = new javax.swing.JLabel();
        jTextField_searchField = new javax.swing.JTextField();
        jButton_search = new javax.swing.JButton();
        jLabel_appName = new javax.swing.JLabel();
        jLabel_commentHome = new javax.swing.JLabel();
        jScrollPane_allComments = new javax.swing.JScrollPane();
        jTable_commentTable = new javax.swing.JTable();
        jPanel_appInfo = new javax.swing.JPanel();
        jLabel_name = new javax.swing.JLabel();
        jScrollPane_scrollComment = new javax.swing.JScrollPane();
        jTextArea_comment = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(2, 48, 71));

        jPanel_sidePanel.setBackground(new java.awt.Color(235, 183, 3));

        jLabel_dashboard.setFont(new java.awt.Font("Lucida Grande", 0, 17)); // NOI18N
        jLabel_dashboard.setForeground(new java.awt.Color(2, 48, 71));
        jLabel_dashboard.setText("DASHBOARD");
        jLabel_dashboard.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_dashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_dashboardMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel_sidePanelLayout = new javax.swing.GroupLayout(jPanel_sidePanel);
        jPanel_sidePanel.setLayout(jPanel_sidePanelLayout);
        jPanel_sidePanelLayout.setHorizontalGroup(
            jPanel_sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_sidePanelLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel_dashboard)
                .addGap(50, 50, 50))
        );
        jPanel_sidePanelLayout.setVerticalGroup(
            jPanel_sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_sidePanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel_dashboard)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel_topPanel.setBackground(new java.awt.Color(235, 183, 3));
        jPanel_topPanel.setName(""); // NOI18N

        jLabel_minimize.setFont(new java.awt.Font("Lucida Grande", 0, 30)); // NOI18N
        jLabel_minimize.setForeground(new java.awt.Color(2, 48, 71));
        jLabel_minimize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_minimize.setText("-");
        jLabel_minimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_minimizeMouseClicked(evt);
            }
        });

        jLabel_close.setFont(new java.awt.Font("Lucida Grande", 0, 30)); // NOI18N
        jLabel_close.setForeground(new java.awt.Color(2, 48, 71));
        jLabel_close.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_close.setText("x");
        jLabel_close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_closeMouseClicked(evt);
            }
        });

        jTextField_searchField.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N

        jButton_search.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        jButton_search.setForeground(new java.awt.Color(2, 48, 71));
        jButton_search.setText("Search");
        jButton_search.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_searchActionPerformed(evt);
            }
        });

        jLabel_appName.setFont(new java.awt.Font("Gurmukhi MN", 0, 32)); // NOI18N
        jLabel_appName.setForeground(new java.awt.Color(2, 48, 71));
        jLabel_appName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_appName.setText("Apps-R-Us");

        jLabel_commentHome.setFont(new java.awt.Font("Gurmukhi MN", 0, 20)); // NOI18N
        jLabel_commentHome.setForeground(new java.awt.Color(2, 48, 71));
        jLabel_commentHome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_commentHome.setText("Comment List");
        jLabel_commentHome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel_topPanelLayout = new javax.swing.GroupLayout(jPanel_topPanel);
        jPanel_topPanel.setLayout(jPanel_topPanelLayout);
        jPanel_topPanelLayout.setHorizontalGroup(
            jPanel_topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_topPanelLayout.createSequentialGroup()
                .addGroup(jPanel_topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_appName, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_commentHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel_topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_topPanelLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jTextField_searchField, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_search)
                        .addContainerGap(688, Short.MAX_VALUE))
                    .addGroup(jPanel_topPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel_minimize, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_close, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel_topPanelLayout.setVerticalGroup(
            jPanel_topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_topPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_topPanelLayout.createSequentialGroup()
                        .addGroup(jPanel_topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_minimize)
                            .addComponent(jLabel_close))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel_topPanelLayout.createSequentialGroup()
                        .addGroup(jPanel_topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel_topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jButton_search, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField_searchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel_topPanelLayout.createSequentialGroup()
                                .addComponent(jLabel_appName)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel_commentHome, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 15, Short.MAX_VALUE))))
        );

        jTable_commentTable.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jTable_commentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Comment"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_commentTable.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTable_commentTable.getTableHeader().setReorderingAllowed(false);
        jTable_commentTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_commentTableMouseClicked(evt);
            }
        });
        jScrollPane_allComments.setViewportView(jTable_commentTable);

        jPanel_appInfo.setBackground(new java.awt.Color(2, 48, 71));

        jLabel_name.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel_name.setForeground(new java.awt.Color(255, 255, 255));

        jScrollPane_scrollComment.setBorder(null);

        jTextArea_comment.setEditable(false);
        jTextArea_comment.setBackground(new java.awt.Color(2, 48, 71));
        jTextArea_comment.setColumns(20);
        jTextArea_comment.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jTextArea_comment.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea_comment.setLineWrap(true);
        jTextArea_comment.setRows(5);
        jTextArea_comment.setWrapStyleWord(true);
        jTextArea_comment.setBorder(null);
        jTextArea_comment.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane_scrollComment.setViewportView(jTextArea_comment);

        javax.swing.GroupLayout jPanel_appInfoLayout = new javax.swing.GroupLayout(jPanel_appInfo);
        jPanel_appInfo.setLayout(jPanel_appInfoLayout);
        jPanel_appInfoLayout.setHorizontalGroup(
            jPanel_appInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_appInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_appInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane_scrollComment, javax.swing.GroupLayout.DEFAULT_SIZE, 337, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel_appInfoLayout.setVerticalGroup(
            jPanel_appInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_appInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_name, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane_scrollComment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(74, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel_sidePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane_allComments, javax.swing.GroupLayout.PREFERRED_SIZE, 724, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel_appInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(12, 12, 12))
            .addComponent(jPanel_topPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel_topPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel_sidePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(jPanel_appInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane_allComments, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(80, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel_minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_minimizeMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabel_minimizeMouseClicked

    private void jLabel_closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_closeMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel_closeMouseClicked

    private void jButton_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_searchActionPerformed
        displayFilteredApps();
    }//GEN-LAST:event_jButton_searchActionPerformed

    private void jTable_commentTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_commentTableMouseClicked
        // Display the highlighted app and comment
        int index = jTable_commentTable.getSelectedRow();
        String appName = jTable_commentTable.getValueAt(index, 0).toString();
        Application currApp = Application.getAppComment(appName);
        
        if (currApp != null) {
            jLabel_name.setText("Name: " + currApp.appName);
            jTextArea_comment.setText("Comment: " + currApp.comment);
        }
    }//GEN-LAST:event_jTable_commentTableMouseClicked

    private void jLabel_dashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_dashboardMouseClicked
        DashboardJFrame dash = new DashboardJFrame();
        dash.setVisible(true);
        dash.pack();
        dash.setLocationRelativeTo(null);
        dash.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jLabel_dashboardMouseClicked

    /**
     * Method that performs the filtering
     */
    public ArrayList<Application> filterApps(String input) {
        ArrayList<Application> appsComm = new ArrayList<Application>();
        PreparedStatement ps;
        Statement st;

        try {
            Connection con = ConnectData.getConnection();
            st = con.createStatement();
            ResultSet rs;
            String searchQuery = "SELECT * FROM `AppComment` WHERE CONCAT(`appName`) LIKE '%" + input + "%'";
            
            rs = st.executeQuery(searchQuery);
            Application app;
            
            while(rs.next()) {
                String name = rs.getString("appName");
                String comment = rs.getString("appComment");
                
                app = new Application(name, comment);
                appsComm.add(app);
            }
            
        } catch(Exception ex) {
            System.out.println(ex.getMessage());
        }
        
        return appsComm;
    }
    /**
     * Method that displays the filtered results 
     */
    public void displayFilteredApps() {
        ArrayList<Application> appsComm = filterApps(jTextField_searchField.getText());
        DefaultTableModel tb = new DefaultTableModel();
        
        tb.setColumnIdentifiers(new Object[]{"Name", "Comment"}); 
        
        Object[] newObj = new Object[7];
        for(int i = 0; i < appsComm.size(); i++) {
            newObj[0] = appsComm.get(i).appName;
            newObj[1] = appsComm.get(i).comment;
            tb.addRow(newObj);
        }
        jTable_commentTable.setModel(tb);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CommentListJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_search;
    private javax.swing.JLabel jLabel_appName;
    private javax.swing.JLabel jLabel_close;
    private javax.swing.JLabel jLabel_commentHome;
    private javax.swing.JLabel jLabel_dashboard;
    private javax.swing.JLabel jLabel_minimize;
    private javax.swing.JLabel jLabel_name;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel_appInfo;
    private javax.swing.JPanel jPanel_sidePanel;
    private javax.swing.JPanel jPanel_topPanel;
    private javax.swing.JScrollPane jScrollPane_allComments;
    private javax.swing.JScrollPane jScrollPane_scrollComment;
    private javax.swing.JTable jTable_commentTable;
    private javax.swing.JTextArea jTextArea_comment;
    private javax.swing.JTextField jTextField_searchField;
    // End of variables declaration//GEN-END:variables
}
