
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.border.Border;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Suzy Doan
 */
public class DashboardJFrame extends javax.swing.JFrame {

    /**
     * Creates new form DashboardJFrame
     */
    public DashboardJFrame() {
        initComponents();
        this.setLocationRelativeTo(null); //Center
        Border bd = BorderFactory.createMatteBorder(2, 2, 2, 2, Color.white);
        jPanel1.setBorder(bd);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel_sidePanel = new javax.swing.JPanel();
        jLabel_appName = new javax.swing.JLabel();
        jLabel_home = new javax.swing.JLabel();
        jLabel_user = new javax.swing.JLabel();
        jLabel_logIn = new javax.swing.JLabel();
        jLabel_register = new javax.swing.JLabel();
        jLabel_browse = new javax.swing.JLabel();
        jLabel_byAlphabet = new javax.swing.JLabel();
        jLabel_byCategory = new javax.swing.JLabel();
        jLabel_byPrice = new javax.swing.JLabel();
        jLabel_welcome = new javax.swing.JLabel();
        jPanel_topPanel = new javax.swing.JPanel();
        jLabel_minimize = new javax.swing.JLabel();
        jLabel_close = new javax.swing.JLabel();
        jTextField_searchField = new javax.swing.JTextField();
        jButton_search = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_appsTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(2, 48, 71));

        jPanel_sidePanel.setBackground(new java.awt.Color(235, 183, 3));

        jLabel_appName.setFont(new java.awt.Font("Gurmukhi MN", 0, 32)); // NOI18N
        jLabel_appName.setForeground(new java.awt.Color(2, 48, 71));
        jLabel_appName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_appName.setText("Apps-R-Us");

        jLabel_home.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N
        jLabel_home.setForeground(new java.awt.Color(2, 48, 71));
        jLabel_home.setText("HOME");

        jLabel_user.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N
        jLabel_user.setForeground(new java.awt.Color(2, 48, 71));
        jLabel_user.setText("USER");

        jLabel_logIn.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N
        jLabel_logIn.setForeground(new java.awt.Color(2, 48, 71));
        jLabel_logIn.setText("Log in");
        jLabel_logIn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_logIn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_logInMouseClicked(evt);
            }
        });

        jLabel_register.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N
        jLabel_register.setForeground(new java.awt.Color(2, 48, 71));
        jLabel_register.setText("Register");
        jLabel_register.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_register.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_registerMouseClicked(evt);
            }
        });

        jLabel_browse.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N
        jLabel_browse.setForeground(new java.awt.Color(2, 48, 71));
        jLabel_browse.setText("BROWSE");

        jLabel_byAlphabet.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N
        jLabel_byAlphabet.setForeground(new java.awt.Color(2, 48, 71));
        jLabel_byAlphabet.setText("By Alphabetics");

        jLabel_byCategory.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N
        jLabel_byCategory.setForeground(new java.awt.Color(2, 48, 71));
        jLabel_byCategory.setText("By Categories");

        jLabel_byPrice.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N
        jLabel_byPrice.setForeground(new java.awt.Color(2, 48, 71));
        jLabel_byPrice.setText("By Price");

        jLabel_welcome.setFont(new java.awt.Font("Lucida Grande", 1, 20)); // NOI18N
        jLabel_welcome.setForeground(new java.awt.Color(2, 48, 71));
        jLabel_welcome.setText("WELCOME!");

        javax.swing.GroupLayout jPanel_sidePanelLayout = new javax.swing.GroupLayout(jPanel_sidePanel);
        jPanel_sidePanel.setLayout(jPanel_sidePanelLayout);
        jPanel_sidePanelLayout.setHorizontalGroup(
            jPanel_sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_sidePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_sidePanelLayout.createSequentialGroup()
                        .addComponent(jLabel_appName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel_sidePanelLayout.createSequentialGroup()
                        .addGroup(jPanel_sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel_sidePanelLayout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(jLabel_welcome))
                            .addGroup(jPanel_sidePanelLayout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(jPanel_sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel_logIn)
                                    .addComponent(jLabel_user)
                                    .addComponent(jLabel_register, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(jPanel_sidePanelLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel_sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_browse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel_sidePanelLayout.createSequentialGroup()
                        .addComponent(jLabel_home)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(jPanel_sidePanelLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel_sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_byPrice)
                    .addComponent(jLabel_byCategory)
                    .addComponent(jLabel_byAlphabet))
                .addGap(0, 47, Short.MAX_VALUE))
        );
        jPanel_sidePanelLayout.setVerticalGroup(
            jPanel_sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_sidePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_appName, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel_welcome)
                .addGap(33, 33, 33)
                .addComponent(jLabel_home)
                .addGap(18, 18, 18)
                .addComponent(jLabel_browse)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel_byAlphabet)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel_byCategory, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel_byPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel_user)
                .addGap(18, 18, 18)
                .addComponent(jLabel_logIn)
                .addGap(18, 18, 18)
                .addComponent(jLabel_register)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel_topPanel.setBackground(new java.awt.Color(235, 183, 3));
        jPanel_topPanel.setName(""); // NOI18N

        jLabel_minimize.setFont(new java.awt.Font("Lucida Grande", 0, 30)); // NOI18N
        jLabel_minimize.setForeground(new java.awt.Color(2, 48, 71));
        jLabel_minimize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_minimize.setText("-");
        jLabel_minimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_minimizeMouseClicked(evt);
            }
        });

        jLabel_close.setFont(new java.awt.Font("Lucida Grande", 0, 30)); // NOI18N
        jLabel_close.setForeground(new java.awt.Color(2, 48, 71));
        jLabel_close.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_close.setText("x");
        jLabel_close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_closeMouseClicked(evt);
            }
        });

        jTextField_searchField.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        jTextField_searchField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_searchFieldActionPerformed(evt);
            }
        });

        jButton_search.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jButton_search.setForeground(new java.awt.Color(2, 48, 71));
        jButton_search.setText("Search");
        jButton_search.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_searchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_topPanelLayout = new javax.swing.GroupLayout(jPanel_topPanel);
        jPanel_topPanel.setLayout(jPanel_topPanelLayout);
        jPanel_topPanelLayout.setHorizontalGroup(
            jPanel_topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_topPanelLayout.createSequentialGroup()
                .addComponent(jTextField_searchField, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_search)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel_minimize, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_close, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13))
        );
        jPanel_topPanelLayout.setVerticalGroup(
            jPanel_topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_topPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel_topPanelLayout.createSequentialGroup()
                        .addGroup(jPanel_topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_minimize)
                            .addComponent(jLabel_close))
                        .addGap(0, 32, Short.MAX_VALUE))
                    .addGroup(jPanel_topPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel_topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField_searchField)
                            .addComponent(jButton_search, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))))
                .addContainerGap())
        );

        jTable_appsTable.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N
        jTable_appsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Name", "Category", "Description", "Organization", "Platform", "Link", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_appsTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jTable_appsTable);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel_sidePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel_topPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 714, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 18, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_sidePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel_topPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel_minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_minimizeMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabel_minimizeMouseClicked

    private void jLabel_closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_closeMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel_closeMouseClicked

    private void jLabel_logInMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_logInMouseClicked
        Login_JFrame loginForm = new Login_JFrame();
        loginForm.setVisible(true);
        loginForm.pack();
        loginForm.setLocationRelativeTo(null);
        loginForm.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose(); //Terminate dashboard if login form is clicked
    }//GEN-LAST:event_jLabel_logInMouseClicked

    private void jLabel_registerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_registerMouseClicked
        Register_JFrame registerForm = new Register_JFrame();
        registerForm.setVisible(true);
        registerForm.pack();
        registerForm.setLocationRelativeTo(null);
        registerForm.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose(); //Terminate dashboard if register form is clicked 
    }//GEN-LAST:event_jLabel_registerMouseClicked

    private void jTextField_searchFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_searchFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_searchFieldActionPerformed

    private void jButton_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_searchActionPerformed
        filterApps();
    }//GEN-LAST:event_jButton_searchActionPerformed

    /**
     * Method that displays the filtered results
     */
    public ArrayList<App> listApps(String input) {
        ArrayList<App> appsArr = new ArrayList<App>();
        Statement ps;
        ResultSet rs;
        
        try{
            Connection con = ConnectData.getConnection();
            ps = con.createStatement();
            String searchQuery = "SELECT * FROM `AppInfo` "
                    + "WHERE CONCAT(`name`) LIKE '%input'";
            
            rs = ps.executeQuery(searchQuery);
            App app;
            while(rs.next()) {
                app = new App(rs.getString("name"), rs.getString("category"),
                              rs.getString("description"), rs.getString("organization"),
                              rs.getString("platform"), rs.getString("version"), 
                              rs.getString("link"), rs.getFloat("price"));
                appsArr.add(app);
            }
            
        } catch(Exception ex){
            System.out.println(ex.getMessage());
        }
        
        return appsArr;
    }
    /**
     * Method that performs the filtering
     */
    public void filterApps() {
        ArrayList<App> appsArr = listApps(jTextField_searchField.getText());
        DefaultTableModel tb = new DefaultTableModel();
        tb.setColumnIdentifiers(new Object[]{"Name", "Category", "Description",
                                "Organization", "Platform", "Version", 
                                "Link", "Price"});
        Object[] newObj = new Object[8];
        for(int i = 0; i < appsArr.size(); i++) {
            newObj[0] = appsArr.get(i).getName();
            newObj[1] = appsArr.get(i).getCategory();
            newObj[2] = appsArr.get(i).getDescription();
            newObj[3] = appsArr.get(i).getOrganization();
            newObj[4] = appsArr.get(i).getPlatform();
            newObj[5] = appsArr.get(i).getVersion();
            newObj[6] = appsArr.get(i).getLink();
            newObj[7] = appsArr.get(i).getPrice();
            tb.addRow(newObj);
        }
        jTable_appsTable.setModel(tb);
        
        /**
         * ArrayList<User> users = ListUsers(jText_Search.getText());
        DefaultTableModel model = new DefaultTableModel();
        model.setColumnIdentifiers(new Object[]{"ID","Fname","Lname","Age"});
        Object[] row = new Object[4];
        
        for(int i = 0; i < users.size(); i++)
        {
            row[0] = users.get(i).getId();
            row[1] = users.get(i).getFname();
            row[2] = users.get(i).getLname();
            row[3] = users.get(i).getAge();
            model.addRow(row);
        }
       jTable_Users.setModel(model);
         */
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashboardJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_search;
    private javax.swing.JLabel jLabel_appName;
    private javax.swing.JLabel jLabel_browse;
    private javax.swing.JLabel jLabel_byAlphabet;
    private javax.swing.JLabel jLabel_byCategory;
    private javax.swing.JLabel jLabel_byPrice;
    private javax.swing.JLabel jLabel_close;
    private javax.swing.JLabel jLabel_home;
    private javax.swing.JLabel jLabel_logIn;
    private javax.swing.JLabel jLabel_minimize;
    private javax.swing.JLabel jLabel_register;
    private javax.swing.JLabel jLabel_user;
    public javax.swing.JLabel jLabel_welcome;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel_sidePanel;
    private javax.swing.JPanel jPanel_topPanel;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable_appsTable;
    private javax.swing.JTextField jTextField_searchField;
    // End of variables declaration//GEN-END:variables
}
