
import java.awt.Color;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.border.Border;


public class Register_JFrame extends javax.swing.JFrame {

    /**
     * Creates new form Register_JFrame
     */
    public Register_JFrame() {
        initComponents();
        this.setLocationRelativeTo(null); //Center
        Border bd = BorderFactory.createMatteBorder(2, 2, 2, 2, Color.white);
        jPanel1.setBorder(bd);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel_portal = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel_close = new javax.swing.JLabel();
        jLabel_goToDashboard = new javax.swing.JLabel();
        jLabel_minimizeWindow1 = new javax.swing.JLabel();
        jPanel_register = new javax.swing.JPanel();
        jTextField_username = new javax.swing.JTextField();
        jLabel_user = new javax.swing.JLabel();
        jLabel_pass = new javax.swing.JLabel();
        jPasswordField_password1 = new javax.swing.JPasswordField();
        jPasswordField_password2 = new javax.swing.JPasswordField();
        jLabel_displayPass = new javax.swing.JLabel();
        jCheckBox_displayPass = new javax.swing.JCheckBox();
        jButton_register = new javax.swing.JButton();
        jLabel_pass2 = new javax.swing.JLabel();
        jLabel_pass3 = new javax.swing.JLabel();
        jLabel_question = new javax.swing.JLabel();
        jLabel_register = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(480, 650));

        jPanel1.setBackground(new java.awt.Color(2, 48, 71));
        jPanel1.setAutoscrolls(true);

        jPanel_portal.setBackground(new java.awt.Color(235, 183, 3));

        jLabel2.setBackground(new java.awt.Color(235, 183, 55));
        jLabel2.setFont(new java.awt.Font("Gurmukhi MN", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(61, 90, 128));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Register Portal");

        javax.swing.GroupLayout jPanel_portalLayout = new javax.swing.GroupLayout(jPanel_portal);
        jPanel_portal.setLayout(jPanel_portalLayout);
        jPanel_portalLayout.setHorizontalGroup(
            jPanel_portalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_portalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel_portalLayout.setVerticalGroup(
            jPanel_portalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_portalLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(27, 27, 27))
        );

        jLabel_close.setBackground(new java.awt.Color(2, 48, 71));
        jLabel_close.setFont(new java.awt.Font("Lucida Grande", 0, 28)); // NOI18N
        jLabel_close.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_close.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_close.setText("x");
        jLabel_close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_close.setOpaque(true);
        jLabel_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_closeMouseClicked(evt);
            }
        });

        jLabel_goToDashboard.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel_goToDashboard.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_goToDashboard.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_goToDashboard.setText("Go to dashboard");
        jLabel_goToDashboard.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_goToDashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_goToDashboardMouseClicked(evt);
            }
        });

        jLabel_minimizeWindow1.setBackground(new java.awt.Color(2, 48, 71));
        jLabel_minimizeWindow1.setFont(new java.awt.Font("Lucida Grande", 0, 28)); // NOI18N
        jLabel_minimizeWindow1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_minimizeWindow1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_minimizeWindow1.setText("-");
        jLabel_minimizeWindow1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_minimizeWindow1.setOpaque(true);
        jLabel_minimizeWindow1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_minimizeWindow1MouseClicked(evt);
            }
        });

        jPanel_register.setBackground(new java.awt.Color(2, 48, 71));

        jTextField_username.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jTextField_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_usernameActionPerformed(evt);
            }
        });

        jLabel_user.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel_user.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_user.setText("Username");

        jLabel_pass.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel_pass.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_pass.setText("Password");

        jPasswordField_password1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jPasswordField_password1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField_password1ActionPerformed(evt);
            }
        });

        jPasswordField_password2.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jPasswordField_password2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField_password2ActionPerformed(evt);
            }
        });

        jLabel_displayPass.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel_displayPass.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_displayPass.setText("Show password");

        jCheckBox_displayPass.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jCheckBox_displayPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox_displayPassActionPerformed(evt);
            }
        });

        jButton_register.setBackground(new java.awt.Color(255, 255, 255));
        jButton_register.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jButton_register.setForeground(new java.awt.Color(61, 90, 128));
        jButton_register.setText("Register");
        jButton_register.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_registerActionPerformed(evt);
            }
        });

        jLabel_pass2.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel_pass2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_pass2.setText("Retype");

        jLabel_pass3.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel_pass3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_pass3.setText("Password");

        jLabel_question.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel_question.setForeground(new java.awt.Color(204, 204, 204));
        jLabel_question.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_question.setText("Already have an account?");

        jLabel_register.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel_register.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_register.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_register.setText("Log in");
        jLabel_register.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_register.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_registerMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel_registerLayout = new javax.swing.GroupLayout(jPanel_register);
        jPanel_register.setLayout(jPanel_registerLayout);
        jPanel_registerLayout.setHorizontalGroup(
            jPanel_registerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_registerLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel_registerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_registerLayout.createSequentialGroup()
                        .addComponent(jLabel_pass)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPasswordField_password1, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_registerLayout.createSequentialGroup()
                        .addGroup(jPanel_registerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel_registerLayout.createSequentialGroup()
                                .addGroup(jPanel_registerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel_registerLayout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jLabel_pass2))
                                    .addGroup(jPanel_registerLayout.createSequentialGroup()
                                        .addComponent(jLabel_pass3)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel_registerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton_register, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPasswordField_password2, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel_registerLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel_registerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel_register, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel_question, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(76, 76, 76)))
                        .addGap(12, 12, 12))))
            .addGroup(jPanel_registerLayout.createSequentialGroup()
                .addGroup(jPanel_registerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_registerLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel_user)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField_username, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel_registerLayout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(jCheckBox_displayPass)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_displayPass)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_registerLayout.setVerticalGroup(
            jPanel_registerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_registerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_registerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_user, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_username, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel_registerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_pass, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPasswordField_password1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel_registerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel_registerLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPasswordField_password2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel_registerLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel_pass2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel_pass3)))
                .addGap(18, 18, 18)
                .addGroup(jPanel_registerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jCheckBox_displayPass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_displayPass, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton_register, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(jLabel_question)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_register)
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jPanel_register, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jPanel_portal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel_minimizeWindow1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_close, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel_goToDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(124, 124, 124))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_close, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_minimizeWindow1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(31, 31, 31)
                .addComponent(jPanel_portal, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel_register, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel_goToDashboard)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(6, 6, 6))
        );

        pack();
    }// </editor-fold>                        

    private void jLabel_registerMouseClicked(java.awt.event.MouseEvent evt) {                                             
        Login_JFrame loginForm = new Login_JFrame();
        loginForm.setVisible(true);
        loginForm.pack();
        loginForm.setLocationRelativeTo(null);
        loginForm.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }                                            

    private void jLabel_closeMouseClicked(java.awt.event.MouseEvent evt) {                                          
        System.exit(0);
    }                                         

    private void jLabel_minimizeWindow1MouseClicked(java.awt.event.MouseEvent evt) {                                                    
        this.setState(JFrame.ICONIFIED);
    }                                                   

    private void jCheckBox_displayPassActionPerformed(java.awt.event.ActionEvent evt) {                                                      
        if(jCheckBox_displayPass.isSelected()) {
            jPasswordField_password1.setEchoChar((char)0);
            jPasswordField_password2.setEchoChar((char)0);
        } else {
            jPasswordField_password1.setEchoChar('*');
            jPasswordField_password2.setEchoChar('*');
        }
    }                                                     

    private void jButton_registerActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        String username = jTextField_username.getText();
        String password = String.valueOf(jPasswordField_password1.getPassword());
        String passwordretype = String.valueOf(jPasswordField_password2.getPassword());
        
        // Check for null username and password, and check if password confirmation matches
        if (username.trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Username cannot be blank.");
        } else if (password.trim().equals("")) {
            JOptionPane.showMessageDialog(null, "Password cannot be blank.");
        } else if (!passwordretype.equals(password)) {
            JOptionPane.showMessageDialog(null, "Password mismatch. Please retype.");
        } else if (checkUsername(username) ) {
            JOptionPane.showMessageDialog(null, "Username already existed. Enter a new username.");
        } else { // If non-null and passwords match, create new user instance
            PreparedStatement ps;
            String query = "INSERT INTO `UserInfo`(`username`, `userPassword`) VALUES (?,?)";
            try {
                ps = ConnectData.getConnection().prepareStatement(query);
                ps.setString(1, username); 
                ps.setString(2, password);

                if(ps.executeUpdate() > 0) {
                    JOptionPane.showMessageDialog(null, "You have successfully registered!");
                }
                
            } catch (SQLException ex) {
                Logger.getLogger(Register_JFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }                                                

    public boolean checkUsername(String username) {
        PreparedStatement ps;
        ResultSet rs;
        boolean userExist = false;
        
        String query = "SELECT * FROM `UserInfo` WHERE `username`=?";
        try {
            ps = ConnectData.getConnection().prepareStatement(query);
            ps.setString(1, username); 
            rs = ps.executeQuery();
            
            if(rs.next()) {
                userExist = true;
            }
        } catch (SQLException ex) {
            Logger.getLogger(Register_JFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
            
        return userExist;
    }
    
    
    private void jPasswordField_password1ActionPerformed(java.awt.event.ActionEvent evt) {                                                         
        // TODO add your handling code here:
    }                                                        

    private void jTextField_usernameActionPerformed(java.awt.event.ActionEvent evt) {                                                    
        // TODO add your handling code here:
    }                                                   

    private void jPasswordField_password2ActionPerformed(java.awt.event.ActionEvent evt) {                                                         
        // TODO add your handling code here:
    }                                                        

    private void jLabel_goToDashboardMouseClicked(java.awt.event.MouseEvent evt) {                                                  
        DashboardJFrame dashboard = new DashboardJFrame();
        dashboard.setVisible(true);
        dashboard.pack();
        dashboard.setLocationRelativeTo(null);
        dashboard.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose(); //Terminate register form if dashboard appears
    }                                                 

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register_JFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton_register;
    private javax.swing.JCheckBox jCheckBox_displayPass;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel_close;
    private javax.swing.JLabel jLabel_displayPass;
    private javax.swing.JLabel jLabel_goToDashboard;
    private javax.swing.JLabel jLabel_minimizeWindow1;
    private javax.swing.JLabel jLabel_pass;
    private javax.swing.JLabel jLabel_pass2;
    private javax.swing.JLabel jLabel_pass3;
    private javax.swing.JLabel jLabel_question;
    private javax.swing.JLabel jLabel_register;
    private javax.swing.JLabel jLabel_user;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel_portal;
    private javax.swing.JPanel jPanel_register;
    private javax.swing.JPasswordField jPasswordField_password1;
    private javax.swing.JPasswordField jPasswordField_password2;
    private javax.swing.JTextField jTextField_username;
    // End of variables declaration                   
}
