
import java.awt.Color;
import java.awt.Font;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.border.Border;
import javax.swing.table.DefaultTableModel;


public class RequestListJFrame extends javax.swing.JFrame {

    /**
     * Creates new form RequestListJFrame
     */
    public RequestListJFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
        Border bd = BorderFactory.createMatteBorder(2, 2, 2, 2, Color.white);
        jPanel1.setBorder(bd);
        
        displayFilteredApps(); // Connect with database
        jTable_appsTable.getTableHeader().setBackground(new Color(240, 239, 235));
        jTable_appsTable.getTableHeader().setFont(new Font("Lucida Grande", Font.BOLD, 15));
        jTable_appsTable.setSelectionBackground(new Color(2,48,71));
        jTable_appsTable.setSelectionForeground(new Color(235,183,3));
        jTable_appsTable.setBackground(new Color(240, 239, 235));
        jTable_appsTable.setRowHeight(50);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel_sidePanel = new javax.swing.JPanel();
        jLabel_dashboard = new javax.swing.JLabel();
        jPanel_topPanel = new javax.swing.JPanel();
        jLabel_minimize = new javax.swing.JLabel();
        jLabel_close = new javax.swing.JLabel();
        jLabel_appName = new javax.swing.JLabel();
        jTextField_searchField = new javax.swing.JTextField();
        jButton_search = new javax.swing.JButton();
        jLabel_requestHome = new javax.swing.JLabel();
        jScrollPane_allApps = new javax.swing.JScrollPane();
        jTable_appsTable = new javax.swing.JTable();
        jButton_accept = new javax.swing.JButton();
        jButton_deny = new javax.swing.JButton();
        jPanel_appInfo3 = new javax.swing.JPanel();
        jLabel_name3 = new javax.swing.JLabel();
        jLabel_organization3 = new javax.swing.JLabel();
        jLabel_platform3 = new javax.swing.JLabel();
        jLabel_version3 = new javax.swing.JLabel();
        jLabel_price3 = new javax.swing.JLabel();
        jScrollPane_description3 = new javax.swing.JScrollPane();
        jTextArea_description3 = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(2, 48, 71));

        jPanel_sidePanel.setBackground(new java.awt.Color(235, 183, 3));
        jPanel_sidePanel.setMaximumSize(new java.awt.Dimension(200, 44));

        jLabel_dashboard.setFont(new java.awt.Font("Lucida Grande", 0, 17)); // NOI18N
        jLabel_dashboard.setForeground(new java.awt.Color(2, 48, 71));
        jLabel_dashboard.setText("DASHBOARD");
        jLabel_dashboard.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_dashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_dashboardMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel_sidePanelLayout = new javax.swing.GroupLayout(jPanel_sidePanel);
        jPanel_sidePanel.setLayout(jPanel_sidePanelLayout);
        jPanel_sidePanelLayout.setHorizontalGroup(
            jPanel_sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_sidePanelLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel_dashboard)
                .addGap(50, 50, 50))
        );
        jPanel_sidePanelLayout.setVerticalGroup(
            jPanel_sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_sidePanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel_dashboard)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel_topPanel.setBackground(new java.awt.Color(235, 183, 3));
        jPanel_topPanel.setName(""); // NOI18N

        jLabel_minimize.setFont(new java.awt.Font("Lucida Grande", 0, 30)); // NOI18N
        jLabel_minimize.setForeground(new java.awt.Color(2, 48, 71));
        jLabel_minimize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_minimize.setText("-");
        jLabel_minimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_minimizeMouseClicked(evt);
            }
        });

        jLabel_close.setFont(new java.awt.Font("Lucida Grande", 0, 30)); // NOI18N
        jLabel_close.setForeground(new java.awt.Color(2, 48, 71));
        jLabel_close.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_close.setText("x");
        jLabel_close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_closeMouseClicked(evt);
            }
        });

        jLabel_appName.setFont(new java.awt.Font("Gurmukhi MN", 0, 32)); // NOI18N
        jLabel_appName.setForeground(new java.awt.Color(2, 48, 71));
        jLabel_appName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_appName.setText("Apps-R-Us");

        jTextField_searchField.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        jTextField_searchField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_searchFieldActionPerformed(evt);
            }
        });

        jButton_search.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jButton_search.setForeground(new java.awt.Color(2, 48, 71));
        jButton_search.setText("Search");
        jButton_search.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_searchActionPerformed(evt);
            }
        });

        jLabel_requestHome.setFont(new java.awt.Font("Gurmukhi MN", 0, 20)); // NOI18N
        jLabel_requestHome.setForeground(new java.awt.Color(2, 48, 71));
        jLabel_requestHome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_requestHome.setText("Request List");
        jLabel_requestHome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel_topPanelLayout = new javax.swing.GroupLayout(jPanel_topPanel);
        jPanel_topPanel.setLayout(jPanel_topPanelLayout);
        jPanel_topPanelLayout.setHorizontalGroup(
            jPanel_topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_topPanelLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel_topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel_appName, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                    .addComponent(jLabel_requestHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel_topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_topPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel_minimize, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_close, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel_topPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jTextField_searchField, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_search)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel_topPanelLayout.setVerticalGroup(
            jPanel_topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_topPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_minimize)
                    .addComponent(jLabel_close))
                .addGap(1, 1, 1)
                .addGroup(jPanel_topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_search, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_searchField))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_topPanelLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(jLabel_appName, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_requestHome)
                .addContainerGap())
        );

        jTable_appsTable.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jTable_appsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Description", "Organization", "Platform", "Version", "Link", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_appsTable.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTable_appsTable.getTableHeader().setReorderingAllowed(false);
        jTable_appsTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_appsTableMouseClicked(evt);
            }
        });
        jScrollPane_allApps.setViewportView(jTable_appsTable);

        jButton_accept.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        jButton_accept.setText("Accept Request");
        jButton_accept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_acceptActionPerformed(evt);
            }
        });

        jButton_deny.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        jButton_deny.setText("Deny Request");
        jButton_deny.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_denyActionPerformed(evt);
            }
        });

        jPanel_appInfo3.setBackground(new java.awt.Color(2, 48, 71));

        jLabel_name3.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel_name3.setForeground(new java.awt.Color(255, 255, 255));

        jLabel_organization3.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel_organization3.setForeground(new java.awt.Color(255, 255, 255));

        jLabel_platform3.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel_platform3.setForeground(new java.awt.Color(255, 255, 255));

        jLabel_version3.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel_version3.setForeground(new java.awt.Color(255, 255, 255));

        jLabel_price3.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel_price3.setForeground(new java.awt.Color(255, 255, 255));

        jScrollPane_description3.setBorder(null);

        jTextArea_description3.setEditable(false);
        jTextArea_description3.setBackground(new java.awt.Color(2, 48, 71));
        jTextArea_description3.setColumns(20);
        jTextArea_description3.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jTextArea_description3.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea_description3.setLineWrap(true);
        jTextArea_description3.setRows(5);
        jTextArea_description3.setWrapStyleWord(true);
        jTextArea_description3.setBorder(null);
        jTextArea_description3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane_description3.setViewportView(jTextArea_description3);

        jScrollPane4.setBorder(null);

        jTextArea4.setEditable(false);
        jTextArea4.setBackground(new java.awt.Color(2, 48, 71));
        jTextArea4.setColumns(20);
        jTextArea4.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jTextArea4.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea4.setLineWrap(true);
        jTextArea4.setRows(5);
        jTextArea4.setWrapStyleWord(true);
        jTextArea4.setBorder(null);
        jScrollPane4.setViewportView(jTextArea4);

        javax.swing.GroupLayout jPanel_appInfo3Layout = new javax.swing.GroupLayout(jPanel_appInfo3);
        jPanel_appInfo3.setLayout(jPanel_appInfo3Layout);
        jPanel_appInfo3Layout.setHorizontalGroup(
            jPanel_appInfo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_appInfo3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_appInfo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_name3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_organization3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_platform3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_version3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_price3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane_description3, javax.swing.GroupLayout.DEFAULT_SIZE, 362, Short.MAX_VALUE)
                    .addComponent(jScrollPane4))
                .addContainerGap())
        );
        jPanel_appInfo3Layout.setVerticalGroup(
            jPanel_appInfo3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_appInfo3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel_name3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane_description3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel_organization3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel_platform3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel_version3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(jLabel_price3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel_topPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel_sidePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(168, 168, 168)
                                .addComponent(jButton_accept, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(91, 91, 91)
                                .addComponent(jButton_deny, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane_allApps, javax.swing.GroupLayout.PREFERRED_SIZE, 695, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(408, 408, 408)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(935, 935, 935)
                    .addComponent(jPanel_appInfo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(17, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel_topPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel_sidePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jScrollPane_allApps, javax.swing.GroupLayout.DEFAULT_SIZE, 389, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton_accept, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_deny, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31))))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(108, 108, 108)
                    .addComponent(jPanel_appInfo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(33, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel_minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_minimizeMouseClicked
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabel_minimizeMouseClicked

    private void jLabel_closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_closeMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jLabel_closeMouseClicked

    private void jTable_appsTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_appsTableMouseClicked
        // Display the highlighted app
        int index = jTable_appsTable.getSelectedRow();
        String appName = jTable_appsTable.getValueAt(index, 0).toString();
        Application currApp = Application.getAppByName("AppRequest", appName);
        
        if (currApp != null) {
            jLabel_name3.setText("Name: " + currApp.appName);
            jTextArea_description3.setText("Description: " + currApp.description);
            jLabel_organization3.setText("Organization: " + currApp.organization);
            jLabel_platform3.setText("Platform: " + currApp.platform);
            jLabel_version3.setText("Version: " + String.valueOf(currApp.version));
            jTextArea4.setText("Link: " + currApp.linkToStore);
            jLabel_price3.setText("Price: $" + String.valueOf(currApp.price));
        }
    }//GEN-LAST:event_jTable_appsTableMouseClicked

    private void jTextField_searchFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_searchFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_searchFieldActionPerformed

    private void jButton_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_searchActionPerformed
        displayFilteredApps();
    }//GEN-LAST:event_jButton_searchActionPerformed

    private void jButton_acceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_acceptActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_acceptActionPerformed

    private void jButton_denyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_denyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_denyActionPerformed

    private void jLabel_dashboardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_dashboardMouseClicked
        DashboardJFrame dash = new DashboardJFrame();
        dash.setVisible(true);
        dash.pack();
        dash.setLocationRelativeTo(null);
        dash.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }//GEN-LAST:event_jLabel_dashboardMouseClicked

     /**
     * Method that performs the filtering
     */
    public ArrayList<Application> filterApps(String input) {
        ArrayList<Application> appsArr = new ArrayList<Application>();
        PreparedStatement ps;
        Statement st;

        try {
            Connection con = ConnectData.getConnection();
            st = con.createStatement();
            ResultSet rs;
            String searchQuery = "SELECT * FROM `AppRequest` WHERE CONCAT(`appName`) LIKE '%" + input + "%'";
            
            rs = st.executeQuery(searchQuery);
            Application app;
            
            while(rs.next()) {
                String name = rs.getString("appName");
                String description = rs.getString("appDescription");
                String organization = rs.getString("appOrganization");
                String platform = rs.getString("appPlatform");
                String version = rs.getString("appVersion");
                String link = rs.getString("appLink");
                double price = rs.getDouble("appPrice");
                
                app = new Application(name, description, organization, platform, version, link, price);
                appsArr.add(app);
            }
            
        } catch(Exception ex) {
            System.out.println(ex.getMessage());
        }
        
        return appsArr;
    }
    /**
     * Method that displays the filtered results 
     */
    public void displayFilteredApps() {
        ArrayList<Application> appsArr = filterApps(jTextField_searchField.getText());
        DefaultTableModel tb = new DefaultTableModel();
        
        tb.setColumnIdentifiers(new Object[]{"Name", "Description",
                                "Organization", "Platform", "Version", 
                                "Link", "Price"}); 
        
        Object[] newObj = new Object[7];
        for(int i = 0; i < appsArr.size(); i++) {
            newObj[0] = appsArr.get(i).appName;
            newObj[1] = appsArr.get(i).description;
            newObj[2] = appsArr.get(i).organization;
            newObj[3] = appsArr.get(i).platform;
            newObj[4] = appsArr.get(i).version;
            newObj[5] = appsArr.get(i).linkToStore;
            newObj[6] = appsArr.get(i).price;
            tb.addRow(newObj);
        }
        jTable_appsTable.setModel(tb);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RequestListJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RequestListJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RequestListJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RequestListJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RequestListJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_accept;
    private javax.swing.JButton jButton_deny;
    private javax.swing.JButton jButton_search;
    private javax.swing.JLabel jLabel_appName;
    private javax.swing.JLabel jLabel_close;
    private javax.swing.JLabel jLabel_dashboard;
    private javax.swing.JLabel jLabel_minimize;
    private javax.swing.JLabel jLabel_name;
    private javax.swing.JLabel jLabel_name1;
    private javax.swing.JLabel jLabel_name2;
    private javax.swing.JLabel jLabel_name3;
    private javax.swing.JLabel jLabel_organization;
    private javax.swing.JLabel jLabel_organization1;
    private javax.swing.JLabel jLabel_organization2;
    private javax.swing.JLabel jLabel_organization3;
    private javax.swing.JLabel jLabel_platform;
    private javax.swing.JLabel jLabel_platform1;
    private javax.swing.JLabel jLabel_platform2;
    private javax.swing.JLabel jLabel_platform3;
    private javax.swing.JLabel jLabel_price;
    private javax.swing.JLabel jLabel_price1;
    private javax.swing.JLabel jLabel_price2;
    private javax.swing.JLabel jLabel_price3;
    private javax.swing.JLabel jLabel_requestHome;
    private javax.swing.JLabel jLabel_version;
    private javax.swing.JLabel jLabel_version1;
    private javax.swing.JLabel jLabel_version2;
    private javax.swing.JLabel jLabel_version3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel_appInfo;
    private javax.swing.JPanel jPanel_appInfo1;
    private javax.swing.JPanel jPanel_appInfo2;
    private javax.swing.JPanel jPanel_appInfo3;
    private javax.swing.JPanel jPanel_sidePanel;
    private javax.swing.JPanel jPanel_topPanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane_allApps;
    private javax.swing.JScrollPane jScrollPane_description;
    private javax.swing.JScrollPane jScrollPane_description1;
    private javax.swing.JScrollPane jScrollPane_description2;
    private javax.swing.JScrollPane jScrollPane_description3;
    private javax.swing.JTable jTable_appsTable;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JTextArea jTextArea_description;
    private javax.swing.JTextArea jTextArea_description1;
    private javax.swing.JTextArea jTextArea_description2;
    private javax.swing.JTextArea jTextArea_description3;
    private javax.swing.JTextField jTextField_searchField;
    // End of variables declaration//GEN-END:variables
}
