
import java.awt.Color;
import java.awt.Font;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import javax.swing.table.DefaultTableModel;


public class RequestListJFrame extends javax.swing.JFrame {

    /**
     * Creates new form DashboardJFrame
     */
    public RequestListJFrame() {
        initComponents();
        this.setLocationRelativeTo(null); //Center

        Border bd = BorderFactory.createMatteBorder(3, 3, 3, 3, Color.white);
        jPanel1.setBorder(bd);
        
        // jTable
        displayFilteredApps(); // Connect with database
        jTable_appsTable.setSelectionBackground(new Color(2,48,71));
        jTable_appsTable.setSelectionForeground(new Color(235,183,3));
        jTable_appsTable.setBackground(new Color(240, 239, 235));
        jTable_appsTable.setRowHeight(50);
        jTable_appsTable.getTableHeader().setBackground(new Color(240, 239, 235));
        jTable_appsTable.getTableHeader().setFont(new Font("Lucida Grande", Font.BOLD, 15));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel_sidePanel = new javax.swing.JPanel();
        jLabel_dashboard = new javax.swing.JLabel();
        jPanel_topPanel = new javax.swing.JPanel();
        jLabel_minimize = new javax.swing.JLabel();
        jLabel_close = new javax.swing.JLabel();
        jTextField_searchField = new javax.swing.JTextField();
        jButton_search = new javax.swing.JButton();
        jLabel_appName = new javax.swing.JLabel();
        jLabel_requestHome = new javax.swing.JLabel();
        jScrollPane_allApps = new javax.swing.JScrollPane();
        jTable_appsTable = new javax.swing.JTable();
        jPanel_appInfo = new javax.swing.JPanel();
        jLabel_name = new javax.swing.JLabel();
        jLabel_organization = new javax.swing.JLabel();
        jLabel_platform = new javax.swing.JLabel();
        jLabel_version = new javax.swing.JLabel();
        jLabel_price = new javax.swing.JLabel();
        jScrollPane_description = new javax.swing.JScrollPane();
        jTextArea_description = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton_deny = new javax.swing.JButton();
        jButton_accept = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(2, 48, 71));

        jPanel_sidePanel.setBackground(new java.awt.Color(235, 183, 3));

        jLabel_dashboard.setFont(new java.awt.Font("Lucida Grande", 0, 17)); // NOI18N
        jLabel_dashboard.setForeground(new java.awt.Color(2, 48, 71));
        jLabel_dashboard.setText("DASHBOARD");
        jLabel_dashboard.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_dashboard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_dashboardMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel_sidePanelLayout = new javax.swing.GroupLayout(jPanel_sidePanel);
        jPanel_sidePanel.setLayout(jPanel_sidePanelLayout);
        jPanel_sidePanelLayout.setHorizontalGroup(
            jPanel_sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_sidePanelLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel_dashboard)
                .addGap(50, 50, 50))
        );
        jPanel_sidePanelLayout.setVerticalGroup(
            jPanel_sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_sidePanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel_dashboard)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel_topPanel.setBackground(new java.awt.Color(235, 183, 3));
        jPanel_topPanel.setName(""); // NOI18N

        jLabel_minimize.setFont(new java.awt.Font("Lucida Grande", 0, 30)); // NOI18N
        jLabel_minimize.setForeground(new java.awt.Color(2, 48, 71));
        jLabel_minimize.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_minimize.setText("-");
        jLabel_minimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_minimizeMouseClicked(evt);
            }
        });

        jLabel_close.setFont(new java.awt.Font("Lucida Grande", 0, 30)); // NOI18N
        jLabel_close.setForeground(new java.awt.Color(2, 48, 71));
        jLabel_close.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_close.setText("x");
        jLabel_close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_closeMouseClicked(evt);
            }
        });

        jTextField_searchField.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N

        jButton_search.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        jButton_search.setForeground(new java.awt.Color(2, 48, 71));
        jButton_search.setText("Search");
        jButton_search.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_searchActionPerformed(evt);
            }
        });

        jLabel_appName.setFont(new java.awt.Font("Gurmukhi MN", 0, 32)); // NOI18N
        jLabel_appName.setForeground(new java.awt.Color(2, 48, 71));
        jLabel_appName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_appName.setText("Apps-R-Us");

        jLabel_requestHome.setFont(new java.awt.Font("Gurmukhi MN", 0, 20)); // NOI18N
        jLabel_requestHome.setForeground(new java.awt.Color(2, 48, 71));
        jLabel_requestHome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_requestHome.setText("Request List");
        jLabel_requestHome.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel_topPanelLayout = new javax.swing.GroupLayout(jPanel_topPanel);
        jPanel_topPanel.setLayout(jPanel_topPanelLayout);
        jPanel_topPanelLayout.setHorizontalGroup(
            jPanel_topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_topPanelLayout.createSequentialGroup()
                .addGroup(jPanel_topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_appName, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_requestHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jPanel_topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_topPanelLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jTextField_searchField, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_search)
                        .addContainerGap(688, Short.MAX_VALUE))
                    .addGroup(jPanel_topPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel_minimize, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_close, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel_topPanelLayout.setVerticalGroup(
            jPanel_topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_topPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_topPanelLayout.createSequentialGroup()
                        .addGroup(jPanel_topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_minimize)
                            .addComponent(jLabel_close))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel_topPanelLayout.createSequentialGroup()
                        .addGroup(jPanel_topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel_topPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jButton_search, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField_searchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel_topPanelLayout.createSequentialGroup()
                                .addComponent(jLabel_appName)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel_requestHome, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 15, Short.MAX_VALUE))))
        );

        jTable_appsTable.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jTable_appsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Description", "Organization", "Platform", "Version", "Link", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_appsTable.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTable_appsTable.getTableHeader().setReorderingAllowed(false);
        jTable_appsTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_appsTableMouseClicked(evt);
            }
        });
        jScrollPane_allApps.setViewportView(jTable_appsTable);

        jPanel_appInfo.setBackground(new java.awt.Color(2, 48, 71));

        jLabel_name.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel_name.setForeground(new java.awt.Color(255, 255, 255));

        jLabel_organization.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel_organization.setForeground(new java.awt.Color(255, 255, 255));

        jLabel_platform.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel_platform.setForeground(new java.awt.Color(255, 255, 255));

        jLabel_version.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel_version.setForeground(new java.awt.Color(255, 255, 255));

        jLabel_price.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel_price.setForeground(new java.awt.Color(255, 255, 255));

        jScrollPane_description.setBorder(null);

        jTextArea_description.setEditable(false);
        jTextArea_description.setBackground(new java.awt.Color(2, 48, 71));
        jTextArea_description.setColumns(20);
        jTextArea_description.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jTextArea_description.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea_description.setLineWrap(true);
        jTextArea_description.setRows(5);
        jTextArea_description.setWrapStyleWord(true);
        jTextArea_description.setBorder(null);
        jTextArea_description.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane_description.setViewportView(jTextArea_description);

        jScrollPane1.setBorder(null);

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(2, 48, 71));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setWrapStyleWord(true);
        jTextArea1.setBorder(null);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel_appInfoLayout = new javax.swing.GroupLayout(jPanel_appInfo);
        jPanel_appInfo.setLayout(jPanel_appInfoLayout);
        jPanel_appInfoLayout.setHorizontalGroup(
            jPanel_appInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_appInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_appInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel_name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_organization, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_platform, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_version, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel_price, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane_description, javax.swing.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        jPanel_appInfoLayout.setVerticalGroup(
            jPanel_appInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_appInfoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_name, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane_description, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel_organization, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel_platform, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel_version, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel_price, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton_deny.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        jButton_deny.setText("Deny Request");
        jButton_deny.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_deny.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_denyActionPerformed(evt);
            }
        });

        jButton_accept.setFont(new java.awt.Font("Lucida Grande", 0, 15)); // NOI18N
        jButton_accept.setText("Accept Request");
        jButton_accept.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_accept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_acceptActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel_sidePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane_allApps, javax.swing.GroupLayout.PREFERRED_SIZE, 724, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addComponent(jButton_accept, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(91, 91, 91)
                        .addComponent(jButton_deny, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel_appInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(12, 12, 12))
            .addComponent(jPanel_topPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel_topPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel_sidePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel_appInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane_allApps, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButton_accept, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton_deny, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(25, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

    private void jLabel_minimizeMouseClicked(java.awt.event.MouseEvent evt) {                                             
        this.setState(JFrame.ICONIFIED);
    }                                            

    private void jLabel_closeMouseClicked(java.awt.event.MouseEvent evt) {                                          
        System.exit(0);
    }                                         

    private void jButton_searchActionPerformed(java.awt.event.ActionEvent evt) {                                               
        displayFilteredApps();
    }                                              

    private void jTable_appsTableMouseClicked(java.awt.event.MouseEvent evt) {                                              
        // Display the highlighted app
        int index = jTable_appsTable.getSelectedRow();
        String appName = jTable_appsTable.getValueAt(index, 0).toString();
        Application currApp = Application.getAppByName("AppRequest", appName);
        
        if (currApp != null) {
            jLabel_name.setText("Name: " + currApp.appName);
            jTextArea_description.setText("Description: " + currApp.description);
            jLabel_organization.setText("Organization: " + currApp.organization);
            jLabel_platform.setText("Platform: " + currApp.platform);
            jLabel_version.setText("Version: " + String.valueOf(currApp.version));
            jTextArea1.setText("Link: " + currApp.linkToStore);
            jLabel_price.setText("Price: $" + String.valueOf(currApp.price));
        }
    }                                             

    private void jLabel_dashboardMouseClicked(java.awt.event.MouseEvent evt) {                                              
        DashboardJFrame dash = new DashboardJFrame();
        dash.setVisible(true);
        dash.pack();
        dash.setLocationRelativeTo(null);
        dash.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.dispose();
    }                                             

    private void jButton_denyActionPerformed(java.awt.event.ActionEvent evt) {                                             
        int index = jTable_appsTable.getSelectedRow();
        String appName = jTable_appsTable.getValueAt(index, 0).toString();
        String deleteQuery = "DELETE FROM `AppRequest` WHERE CONCAT(`appName`) LIKE '%" + appName + "%'";
        PreparedStatement ps;

        try {
            ps = ConnectData.getConnection().prepareStatement(deleteQuery);
            if(ps.executeUpdate() > 0) {
                JOptionPane.showMessageDialog(null, "Add request denied");
            } else {
                JOptionPane.showMessageDialog(null, "Failed to deny request");
            }
        } catch (SQLException ex) {
            Logger.getLogger(Application.class.getName()).log(Level.SEVERE, null, ex);
        }
    }                                            

    private void jButton_acceptActionPerformed(java.awt.event.ActionEvent evt) {                                               
        int index = jTable_appsTable.getSelectedRow();
        String appName = jTable_appsTable.getValueAt(index, 0).toString();
        Application app = Application.getAppByName("AppRequest", appName);
        
        String deleteQuery = "DELETE FROM `AppRequest` WHERE CONCAT(`appName`) LIKE '%" + appName + "%'";
        PreparedStatement ps;

        try {
            ps = ConnectData.getConnection().prepareStatement(deleteQuery);
            ps.execute();
        } catch (SQLException ex) {
            Logger.getLogger(Application.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        app.addAppToDB(appName);
    }                                              

    /**
     * Method that performs the filtering
     */
    public ArrayList<Application> filterApps(String input) {
        ArrayList<Application> appsArr = new ArrayList<Application>();
        PreparedStatement ps;
        Statement st;

        try {
            Connection con = ConnectData.getConnection();
            st = con.createStatement();
            ResultSet rs;
            String searchQuery = "SELECT * FROM `AppRequest` WHERE CONCAT(`appName`) LIKE '%" + input + "%'";
            
            rs = st.executeQuery(searchQuery);
            Application app;
            
            while(rs.next()) {
                String name = rs.getString("appName");
                String description = rs.getString("appDescription");
                String organization = rs.getString("appOrganization");
                String platform = rs.getString("appPlatform");
                String version = rs.getString("appVersion");
                String link = rs.getString("appLink");
                double price = rs.getDouble("appPrice");
                
                app = new Application(name, description, organization, platform, version, link, price);
                appsArr.add(app);
            }
            
        } catch(Exception ex) {
            System.out.println(ex.getMessage());
        }
        
        return appsArr;
    }
    /**
     * Method that displays the filtered results 
     */
    public void displayFilteredApps() {
        ArrayList<Application> appsArr = filterApps(jTextField_searchField.getText());
        DefaultTableModel tb = new DefaultTableModel();
        
        tb.setColumnIdentifiers(new Object[]{"Name", "Description",
                                "Organization", "Platform", "Version", 
                                "Link", "Price"}); 
        
        Object[] newObj = new Object[7];
        for(int i = 0; i < appsArr.size(); i++) {
            newObj[0] = appsArr.get(i).appName;
            newObj[1] = appsArr.get(i).description;
            newObj[2] = appsArr.get(i).organization;
            newObj[3] = appsArr.get(i).platform;
            newObj[4] = appsArr.get(i).version;
            newObj[5] = appsArr.get(i).linkToStore;
            newObj[6] = appsArr.get(i).price;
            tb.addRow(newObj);
        }
        jTable_appsTable.setModel(tb);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RequestListJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton_accept;
    private javax.swing.JButton jButton_deny;
    private javax.swing.JButton jButton_search;
    private javax.swing.JLabel jLabel_appName;
    private javax.swing.JLabel jLabel_close;
    private javax.swing.JLabel jLabel_dashboard;
    private javax.swing.JLabel jLabel_minimize;
    private javax.swing.JLabel jLabel_name;
    private javax.swing.JLabel jLabel_organization;
    private javax.swing.JLabel jLabel_platform;
    private javax.swing.JLabel jLabel_price;
    private javax.swing.JLabel jLabel_requestHome;
    private javax.swing.JLabel jLabel_version;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel_appInfo;
    private javax.swing.JPanel jPanel_sidePanel;
    private javax.swing.JPanel jPanel_topPanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane_allApps;
    private javax.swing.JScrollPane jScrollPane_description;
    private javax.swing.JTable jTable_appsTable;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea_description;
    private javax.swing.JTextField jTextField_searchField;
    // End of variables declaration                   
}
